### ISSUE TITLE
macos updates

### ISSUE THREAD

**Issue by otosky** [otosky/dotfiles#8]
- remove Kitty install
- use abs path for homebrew command on install
- add homebrew to path?
- call `install_fisher` and `fisher update`
- change shell https://gist.github.com/gagarine/cf3f65f9be6aa0e105b184376f765262

**Comment by oliver-tosky-sh** [comment]
add homebrew to path conditionally for fish

add deps
```sh
brew install zlib openssl@1.1 readline libyaml
```

hook brew into shell
```sh
eval "$(/opt/homebrew/bin/brew shellenv)"
```

**Comment by otosky** [comment]
add https://github.com/nikitabobko/AeroSpace
